version: '3'

services:
  # authentication services
  auth-redis:
    restart: always
    image: redis:7.2.4
    volumes:
      - ./docker/authentication/redis:/data
    networks:
      - default

  auth-postgres:
    restart: always
    image: postgres:16.2
    volumes:
      - ./docker/authentication/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: printit
    networks:
      - default

  auth-app:
    restart: always
    build:
      context: .
      dockerfile: auth.Dockerfile
    depends_on:
      - auth-redis
      - auth-postgres
    environment:
      - REST_HOST=0.0.0.0
      - REST_PORT=3000
      - GRPC_ADDR=0.0.0.0:50051
      - PG_HOST=auth-postgres
      - REDIS_URL=redis://auth-redis/0
    ports:
      - "3000:3000"
      - "50051:50051"
    networks:
      - default

  # shop services
  shop-mongo:
    restart: always
    image: mongo:7.0
    volumes:
      - ./docker/shop/mongo:/data/db
    networks:
      - default

  shop-app:
    restart: always
    build:
      context: .
      dockerfile: shop.Dockerfile
    depends_on:
      - auth-app
      - shop-mongo
    environment:
      - REST_PORT=3002
      - GRPC_PORT=50053
      - AUTH_GRPC_URI=http://auth-app:50051
      - MONGO_URI=mongodb://shop-mongo/?maxPoolSize=100
    ports:
      - "3002:3002"
      - "50053:50053"
    networks:
      - default

  # price services
  price-postgres:
    restart: always
    image: postgres:16.2
    volumes:
      - ./docker/price/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: printit
    networks:
      - default

  price-app:
    restart: always
    build:
      context: .
      dockerfile: price.Dockerfile
    depends_on:
      - auth-app
      - shop-app
      - price-postgres
    environment:
      - REST_HOST=0.0.0.0
      - REST_PORT=3003
      - GRPC_ADDR=0.0.0.0:50054
      - PG_HOST=price-postgres
      - AUTH_GRPC_URI=auth-app:50051
      - SHOP_GRPC_URI=shop-app:50053
    ports:
      - "3003:3003"
      - "50054:50054"
    networks:
        - default

networks:
  default: {}
