version: '3'

services:
  redis:
    restart: always
    image: redis:7.2.4
    volumes:
      - ./docker/authentication/redis:/data
    networks:
      - default

  postgres:
    restart: always
    image: postgres:16.2
    volumes:
      - ./docker/authentication/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: users
    networks:
      - default

  app:
    build:
      context: .
      dockerfile: Dockerfile.authentication
    ports:
      - "3000:3000"
    networks:
      - default

networks:
  default: {}
