networks:
    default: {}
services:
    auth-postgres:
        environment:
            POSTGRES_DB: printit
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
        image: postgres:16.2
        networks:
            - default
        restart: always
        volumes:
            - ./docker/authentication/pg:/var/lib/postgresql/data
    auth-redis:
        image: redis:7.2.4
        networks:
            - default
        restart: always
        volumes:
            - ./docker/authentication/redis:/data
version: "3"
