version: '3'

services:
  redis:
    restart: always
    image: redis:7.2.4
    volumes:
      - ./docker/authentication/redis:/data
    networks:
      - default

  postgres:
    restart: always
    image: postgres:16.2
    volumes:
      - ./docker/authentication/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: users
    networks:
      - default

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.authentication
    environment:
      - REST_HOST=0.0.0.0
      - REST_PORT=3000
      - GRPC_ADDR=0.0.0.0:50051
      - PG_HOST=postgres
      - REDIS_URL=redis://redis/0
    ports:
      - "3000:3000"
      - "50051:50051"
    networks:
      - default

networks:
  default: {}
