version: '3'


tasks:

  # authentication server tasks
  auth-docker:
    - docker compose -f ./compose-authentication.yaml up --build
  auth-psql:
    - docker run -e POSTGRES_USER=root -e POSTGRES_PASSWORD=root -e POSTGRES_DB=users -p 5432:5432 postgres
  auth-redis:
    - docker run -p 6379:6379 redis
  auth-proto-gen:
    - python -m grpc_tools.protoc --proto_path=./proto_def/authentication --python_out=./authentication/src/proto_gen --pyi_out=./authentication/src/proto_gen --grpc_python_out=./authentication/src/proto_gen auth.proto



  # file server tasks
  file-proto-gen:
    - protoc --go_out=./file/proto_gen/authentication --go_opt=paths=source_relative --go-grpc_out=./file/proto_gen/authentication --go-grpc_opt=paths=source_relative --proto_path=./proto_def/authentication ./proto_def/authentication/auth.proto
  file-minio:
    - docker run -p 9000:9000 -p 9001:9001 --env MINIO_ROOT_USER=minio-access-key --env MINIO_ROOT_PASSWORD=minio-secret-key bitnami/minio:latest
